import commander from 'commander';
import getAccessToken from './library/getAccessToken';
import getAuthCode from './library/getAuthCode';
import loginToBullhorn from './library/loginToBullhorn';

commander
  .version('1.0.0', '-v, --version')
  .usage('[OPTIONS]...')
  .option('-c, --clientId <clientId>', 'ID generated by Bullhorn which identifies your account')
  .option('-s, --clientSecret <clientSecret>', 'Secret generated by Bullhorn to authenticate into the system')
  .option('-u, --username <username>', 'Bullhorn Username')
  .option('-p, --password <password>', 'Bullhorn Password')
  .parse(process.argv);

const { clientId, clientSecret, username, password } = commander.opts();

(async function authenticateWithBullhorn() {
  try {
    const authCode = await getAuthCode({ clientId, username, password });

    if(!authCode)

    const { accessToken } = await getAccessToken({ clientId, clientSecret, authCode });

    const res = await loginToBullhorn({ accessToken });

    console.log({ res });
  } catch (err) {
    console.error(err);
  }
})();
